ci:
# - color: '#7c0bb2'
any:
- changed-files:
  - any-glob-to-any-file: '.github/*'
color: '#7c0bb2'

labeler:
- changed-files:
  - any-glob-to-any-file: 'labeler/*'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'docs/*'
    - README.md
