name: "Pull Request Labeler"
on:
- pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      id: labeler
      with:
        sync-labels: true
    - run: |
        echo "Labels: ${{ steps.labeler.outputs.all-labels }}"
