name: release
on:
  push:
    tags:
      - "v*"
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: cli/gh-extension-precompile@9e2237c30f869ad3bcaed6a4be2cd43564dd421b # v2.1.0
        with:
          generate_attestations: true
          go_version_file: go.mod
          release_tag: ${{ inputs.ref || github.ref }}

